# Generated by Django 4.1.7 on 2023-04-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='', upload_to='profiles/images/'),
        ),
    ]
