# Generated by Django 4.1.7 on 2023-04-02 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkins", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("checkin", "question")},
        ),
    ]
