# Generated by Django 4.1.7 on 2023-04-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkins", "0002_alter_answer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
