# Generated by Django 4.1.7 on 2023-04-05 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkins", "0004_alter_checkin_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkin",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="checkin",
            unique_together={("user", "created_at")},
        ),
    ]
