# Generated by Django 4.1.7 on 2023-04-05 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("checkins", "0006_feelingtype_feeling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeling",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
