# Generated by Django 4.1.7 on 2023-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkins", "0007_alter_feeling_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="created_at",
            field=models.DateField(),
        ),
    ]
